EXPORT_FUNC(get_version)
EXPORT_FUNC(getc)
EXPORT_FUNC(tstc)
EXPORT_FUNC(putc)
EXPORT_FUNC(puts)
EXPORT_FUNC(printf)
EXPORT_FUNC(install_hdlr)
EXPORT_FUNC(free_hdlr)
EXPORT_FUNC(malloc)
EXPORT_FUNC(free)
EXPORT_FUNC(udelay)
EXPORT_FUNC(get_timer)
EXPORT_FUNC(vprintf)
EXPORT_FUNC(do_reset)
#if (CONFIG_COMMANDS & CFG_CMD_I2C)
EXPORT_FUNC(i2c_write)
EXPORT_FUNC(i2c_read)
#endif	/* CFG_CMD_I2C */
#ifdef CONFIG_EXPORT_ETH_FNS
EXPORT_FUNC(eth_init)
EXPORT_FUNC(eth_halt)
EXPORT_FUNC(eth_send)
EXPORT_FUNC(eth_rx)
EXPORT_FUNC(NetSetHandler)
#endif /* EXPORT_ETH_FNS */
